### ISSUE TITLE
If another package also depends on uglify-js, the after_prepare hook fails

### ISSUE THREAD

**Issue by sdurandeu** [rossmartin/cordova-uglify#22]
Not sure this is actually an issue, as this can be easily fixed by running npm install with the `--legacy-bundling` option (as specified on the README). The problem is that it should be done before running the global `npm install` to restore packages.  It kinds of break the usual workflow of cloning, running npm install, ionic, etc.

The error I'm getting is `Error: Cannot find module '/Users/sdurandeu/Documents/projects/vinti/client/node_modules/cordova-uglify/node_modules/uglify-js'`. 

Is there something I'm missing? What do you think?

Thanks!!

**Comment by rossmartin** [comment]
I think I understand the issue here and will be looking into it.  Thanks.

**Comment by rodrigograca31** [comment]
I'm having the same issue....
I've updated from `"cordova-uglify": "^0.1.9"` to the newest version and now I get this error:
```
Running command: [PROJECT]/hooks/after_prepare/uglify.js [PROJECT]
module.js:338
    throw err;
          ^
Error: Cannot find module '[PROJECT]/node_modules/cordova-uglify/node_modules/ng-annotate'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([PROJECT]/hooks/after_prepare/uglify.js:13:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Error: Hook failed with error code 1: [PROJECT]/hooks/after_prepare/uglify.js
```

Note: This log is complaining about `ng-annotate` not sure why because it was complaining about `uglify-js`... but I've tried a bunch of things to solve it and something worked...

`npm ls uglify-js` returned:
```
├─┬ bower@1.4.1
│ └─┬ handlebars@2.0.0
│   └── uglify-js@2.3.6 
└─┬ cordova-uglify@0.2.4
  └── uglify-js@2.4.14 
```
and `npm ls ng-annotate` returns:
```
└── ng-annotate@0.15.4 
```
So, `ng-annotate` is a main dependency and doesn't get installed for `cordova-uglify` even thought it's specified in the package.json of this project....

**Comment by rossmartin** [comment]
@rodrigograca31 

Try this from the root of your project directory -

`npm uninstall cordova-uglify` (might require sudo)

Then remove all directories in your `/${project}/node_modules` directory before reinstalling -

`sudo rm -r node_modules`

Then run this from your /myproject directory -

`npm install cordova-uglify`

https://github.com/rossmartin/cordova-uglify/issues/18#issuecomment-179342796

**Comment by rodrigograca31** [comment]
It worked! And I was having the same problem as him (#18) ....
and because I use `bower` globally it removed `bower` module from `node_modules` ...

Thanks!

**Comment by JeremyColton** [comment]
I tried uninstalling and then reinstalling as per your comment on 1 Aug but I still get this same error.

My json is the default but with "alwaysRun" : true.

`{
    "alwaysRun": true,
    "recursiveFolderSearch": true,
    "foldersToProcess": [
        "js",
        "css",
        "img",
        "build"
    ],
    "uglifyJsOptions": {
        "compress": {
            "drop_console": true
        },
        "fromString": true,
        "mangle": true
    },
    "cleanCssOptions": {
        "noAdvanced": true,
        "keepSpecialComments": 0
    },
    "imageminOptions": {
        "jpeg": {
            "progressive": true,
            "arithmetic": false
        },
        "png": {
            "optimizationLevel": 2
        },
        "gif": {
            "interlaced": false
        },
        "svg": {
            "pretty": false
        }
    }
}
`
I see this error:

uglifying js file C:\ScoochUp\dev\svn\trunk\Android\SUpMobileApp363_Android\platforms\android\assets\www\js\lib\infinity-jc.js
C:\ScoochUp\dev\svn\trunk\Android\SUpMobileApp363_Android\node_modules\cordova-uglify\node_modules\uglify-js\tools\node.js:75
        files.forEach(function(file){
             ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.exports.minify (C:\ScoochUp\dev\svn\trunk\Android\SUpMobileApp363_Android\node_modules\cordova-uglify\node_modules\uglify
-js\tools\node.js:75:14)
    at compress (C:\ScoochUp\dev\svn\trunk\Android\SUpMobileApp363_Android\hooks\after_prepare\uglify.js:130:25)
    at C:\ScoochUp\dev\svn\trunk\Android\SUpMobileApp363_Android\hooks\after_prepare\uglify.js:97:11
    at FSReqWrap.oncomplete (fs.js:95:15)
Hook failed with error code 1: C:\ScoochUp\dev\svn\trunk\Android\SUpMobileApp363_Android\hooks\after_prepare\uglify.js

Any ideas?

**Comment by JeremyColton** [comment]
Yes - the .js file was invalid according to http://www.jslint.com/
I fixed it and then the uglification finished ok.

So, javascript must be VALID :)

**Comment by rodrigograca31** [comment]
Hi!

I had the same problem again (not sure why) (maybe because I updated to node 7.0.0 a few weeks ago)

The previous commands didn't solve the problem...

Full error:
```
Running command: /home/USER/git/PROJECT/hooks/after_prepare/uglify.js /home/USER/git/PROJECT
module.js:474
    throw err;
    ^

Error: Cannot find module '/home/USER/git/PROJECT/node_modules/cordova-uglify/node_modules/uglify-js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/USER/git/PROJECT/hooks/after_prepare/uglify.js:11:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
Error: Hook failed with error code 1: /home/USER/git/PROJECT/hooks/after_prepare/uglify.js
```

npm ls uglify-js: (only `cordova-uglify` uses `uglify-js`)
```
└─┬ cordova-uglify@0.2.6
  └── uglify-js@2.4.14 
```

but the `cordova-uglify` folder doesn't have a `node_modules` folder inside...
`uglify-js` folder is under `PROJECT/node_modules/` and not `PROJECT/node_modules/cordova-uglify/node_modules/` as the error says...

So, to solve this I edited `PROJECTS/hooks/after_prepare/uglify.js` line 9 from:
```var dependencyPath = path.join(cwd, 'node_modules', 'cordova-uglify', 'node_modules');```
to
```var dependencyPath = path.join(cwd, 'node_modules');```

Is this how node 7 works? Should we edit the plugin code?

Thanks.

**Comment by rossmartin** [comment]
@rodrigograca31 make sure to install with the `--legacy-bundling` option.

```
npm install cordova-uglify --legacy-bundling
```

**Comment by rodrigograca31** [comment]
@rossmartin Hummm, it worked...

So node changed the way it does things?
Should we edit the plugin code?

**Comment by rossmartin** [comment]
@rodrigograca31 I know a way to fix the issue with having to use `--legacy-bundling`.  Once I get time I will be revising how this hooks dependencies are imported.

**Comment by rodrigograca31** [comment]
@rossmartin Ok.

But as I said before I've already solved it without `--legacy-bundling` by editing line 9...

**Comment by rossmartin** [comment]
@rodrigograca31 The problem is making it backwards compatible for those that aren't on npm 3 and higher.

**Comment by rodrigograca31** [comment]
@rossmartin If we don't make breaking changes we don't advance....

That said, What's the percentage? Any way to know?

**Comment by rossmartin** [comment]
@rodrigograca31 I've updated the the hook to not require using the `--legacy-bundling` option.  Thanks, you have a good point, I went ahead and made the change.

I'm not sure how many are using npm lower than 3 but I don't think it is that many anymore.  This issue has been solved as of [0.2.7](https://github.com/rossmartin/cordova-uglify/tree/0.2.7)
